sudo: required
services:
  - docker

script:
  - docker build -t wunggary/node .
  - docker images wunggary/node

before_deploy:
  - docker login -u wunggary -p peiyauwe5250

deploy:
  provider: script
  script: docker push wunggary/node
  on:
    branch: master