sudo: required
services:
  - docker

script:
  - docker build -t mannydesigns/node .
  - docker images mannydesigns/node

before deploy:
  - docker login -u <username> -p <userpassword>

deploy:
  provider: script
  script: docker push mannydesigns/node
  on:
    branch: master