sudo: required
services:
  - docker

script:
  - docker build -t mannydesigns/node .
  - docker images mannydesigns/node

before deploy:
  - docker login -u wunggary -p peiyauwe5250

deploy:
  provider: script
  script: docker push mannydesigns/node
  on:
    branch: master